sudo: false
language: java
jdk:
- oraclejdk7
cache:
  directories:
  - $HOME/.m2
before_install:
# install the gwtjui library before we build the demo
- git clone https://github.com/BenDol/gwt-jui.git
- cd gwt-jui
- mvn install -DskipTests=true -DdryRun=true
- cd ..
install: true
script:
  - mvn clean install -DdryRun=true -Dlicense.failOnMissingHeader=true -Dlicense.failOnNotUptodateHeader=true
after_success:
  - .utility/update_demo_site.sh